name: CI

on:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun x prettier --check .
      - run: bun x tsc --noEmit
      - run: bun test
