name: CI

on:
  push:
  pull_request_target:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun x prettier --check .
      - run: bun x tsc --noEmit
      - run: bun test
        env:
          CRISP_IDENTIFIER: ${{ secrets.CRISP_IDENTIFIER }}
          CRISP_KEY: ${{ secrets.CRISP_KEY }}
          CRISP_PLUGIN_URN: ${{ secrets.CRISP_PLUGIN_URN }}
          CRISP_USER_NICKNAME: ${{ secrets.CRISP_USER_NICKNAME }}
          CRISP_WEBSITE_ID: ${{ secrets.CRISP_WEBSITE_ID }}
